---
- name: install dependencies and libraries
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - blas
    - blas-devel
    - lapack
    - lapack-devel
    - tcl
    - tcllib
    - tcl-devel
    - tk
    - tk-devel
    - bzip2-devel
    - pcre-devel
    - libcurl-devel

- name: create /software
  file:
    path: "{{ software_path }}"
    state: directory
    mode: 0755

# zlib module
- name: download zlib
  get_url:
    url: "{{ zlib_url }}"
    dest: /tmp/{{ zlib_file }}

- name: unarchive zlib
  unarchive:
    src: /tmp/{{ zlib_file }}
    dest: "{{ src_path }}"
    remote_src: yes
    creates: "{{ src_path }}/zlib-{{ zlib_version }}"

- name: install zlib
  shell: ./configure --prefix={{ software_path }}/zlib/{{ zlib_version }} && make && make install
  args:
    chdir: "{{ src_path }}/zlib-{{ zlib_version }}"
    creates: libz.so

- name: create zlib module directory
  file:
    path: "{{ module_path }}/zlib"
    state: directory
    mode: 0755

- name: create zlib module file
  template:
    src: zlib.modulefile
    dest: "{{ module_path }}/zlib/{{ zlib_version }}"

# R